paths:
  checkpoint:
    loss: output/checkpoints/{}-loss.h5
    accuracy: output/checkpoints/{}-accuracy.h5
  plot:
    base: output/plots/{}
    loss: output/plots/{}/loss_b{}_s{}_o{}_c{}.png
    accuracy: output/plots/{}/accuracy_b{}_s{}_o{}_c{}.png
    lr: output/plots/lr.png
training:
  dataset: oxford_flowers102
  mode: categorical
  loss: sparse_categorical_crossentropy