paths:
  checkpoint:
    loss: output/checkpoints/{}-loss.h5
    accuracy: output/checkpoints/{}-accuracy.h5
  plot:
    base: output/plots/{}
    loss: output/plots/{}/loss_b{}_s{}_o{}_c{}_a{}.png
    accuracy: output/plots/{}/accuracy_b{}_s{}_o{}_c{}_a{}.png
    lr: output/plots/lr.png
  data:
    training: data/train
    validation: data/valid
    test: data/test
training:
  dataset: oxford_flowers102
  mode: categorical
  loss: categorical_crossentropy